version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow_server
    ports:
      - "5000:5000"
    env_file:
      - .env  # Reference the .env file
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db

  train:
    image: python:3.12.3
    container_name: train_model
    depends_on:
      - mlflow
    env_file:
      - .env  # Reference the .env file
    working_dir: /app
    volumes:
      - ./train_models.py:/app/train_models.py
      - ./data_processing.py:/app/data_processing.py
      - ./feature_eng.py:/app/feature_eng.py
      - ./configs.json:/app/configs.json
      - ./region_best_params.json:/app/region_best_params.json
      - ./requirements.txt:/app/requirements.txt
      - ./data:/app/data
    command: |
      bash -c "pip install --no-cache-dir -r /app/requirements.txt && python /app/train_models.py"
